
[package]
name = "cocoa"
description = "Bindings to Cocoa for OS X"
homepage = "https://github.com/servo/core-foundation-rs"
repository = "https://github.com/servo/core-foundation-rs"
version = "0.17.0"
authors = ["The Servo Project Developers"]
license = "MIT / Apache-2.0"

[lib]
name = "cocoa"
crate-type = ["rlib"]

[dependencies]
block = "0.1"
bitflags = "1.0"
libc = "0.2"
core-graphics = { path = "../core-graphics", version = "0.17" }
objc = "0.2.3"
