[package]
name = "io-surface"
description = "Bindings to IO Surface for OS X"
homepage = "https://github.com/servo/core-foundation-rs"
repository = "https://github.com/servo/core-foundation-rs"
version = "0.11.1"
authors = ["The Servo Project Developers"]
license = "MIT / Apache-2.0"

[dependencies]
libc = "0.2"
gleam = "0.6"

[target.x86_64-apple-darwin.dependencies]
core-foundation = { path = "../core-foundation", version = "0.6" }
cgl = "0.2.3"
leaky-cow = "0.1.1"
