language: rust
rust: stable
matrix:
  include:
    # macOS 10.12
    - os: osx
      env: TARGET=x86_64-apple-darwin CGFEATURES="--features elcapitan"
    - os: osx
      env: TARGET=i686-apple-darwin CGFEATURES="--features elcapitan"
    # macOS 10.10
    - os: osx
      osx_image: xcode7.2
      env: TARGET=x86_64-apple-darwin CGFEATURES=""
    - os: osx
      osx_image: xcode7.2
      env: TARGET=i686-apple-darwin CGFEATURES=""
    # macOS 10.13
    - os: osx
      osx_image: xcode9.4
      env: TARGET=x86_64-apple-darwin CGFEATURES="--features highsierra,elcapitan"
    - os: osx
      osx_image: xcode9.4
      env: TARGET=i686-apple-darwin CGFEATURES="--features highsierra,elcapitan"
    # test whether docs build on Linux - required for crates.io
    - os: linux
      script: cargo doc --all-targets --verbose

install:
  - rustup target add $TARGET
script:
  - cargo build --all-targets --verbose --target $TARGET
  - cargo test --verbose --target $TARGET -- --nocapture
