[package]
name = "core-foundation-sys"
description = "Bindings to Core Foundation for OS X"
homepage = "https://github.com/servo/core-foundation-rs"
repository = "https://github.com/servo/core-foundation-rs"
version = "0.6.2"
authors = ["The Servo Project Developers"]
license = "MIT / Apache-2.0"
build = "build.rs"

[dependencies]

[features]
mac_os_10_7_support = [] # backwards compatibility
mac_os_10_8_features = [] # enables new features
